CREATE TABLE public."document_types" (
    "id" int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "name" varchar NOT NULL,
    "abbr" varchar NOT NULL,
    "length_type" public."document_length_type" NOT NULL,
    "length" int2 NOT NULL,
    "char_type" public."document_char_type" NOT NULL,
    "created_at" timestamptz(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz(0) NULL,
    "deleted_at" timestamptz(0) NULL,
    UNIQUE NULLS NOT DISTINCT ("name", "deleted_at"),
    UNIQUE NULLS NOT DISTINCT ("abbr", "deleted_at")
)
;

CREATE TABLE public."persons" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "client_id" int4 NULL,
    "document_type_id" int4 NOT NULL,
    "document_number" VARCHAR NOT NULL,
    "first_name" VARCHAR NOT NULL,
    "middle_name" VARCHAR NULL,
    "last_name_paternal" VARCHAR NOT NULL,
    "last_name_maternal" VARCHAR NULL,
    "gender" public."gender" NOT NULL,
    "email" VARCHAR NOT NULL,
    "phone" VARCHAR NULL,
    "created_at" TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(0) NULL,
    UNIQUE NULLS NOT DISTINCT ("email", "deleted_at"),
    UNIQUE NULLS NOT DISTINCT ("client_id", "document_number", "deleted_at")
)
;

CREATE TABLE public."users" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "person_id" INT4 NOT NULL,
    "username" VARCHAR NOT NULL,
    "password" VARCHAR NOT NULL, -- El password debe estar encriptado con argon2 y concatenado con el salt usando este formato: "argon2:{password}:{salt}"
    "avatar_url" varchar NULL,
    "is_verified" bool NOT NULL DEFAULT FALSE,
    "is_super_admin" bool NOT NULL DEFAULT FALSE,
    "last_login_at" timestamptz(0) NULL,
    "enabled" bool NOT NULL DEFAULT TRUE,
    "created_at" TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(0) NULL,
    UNIQUE NULLS NOT DISTINCT ("username", "deleted_at"),
    UNIQUE NULLS NOT DISTINCT ("person_id", "deleted_at")
)
;

CREATE TABLE public."user_sessions" (
    "id" int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "user_id" int4 NOT NULL,
    "token" varchar NOT NULL,
    "expires_at" timestamptz(0) NOT NULL,
    "closed_at" timestamptz(0) NULL,
    "ip" varchar NOT NULL, -- Información sensible que debe estar encriptada.
    "user_agent" varchar NOT NULL, -- Información sensible que debe estar encriptada.
    "last_activity_at" timestamptz(0) NULL,
    "metadata" jsonb NOT NULL DEFAULT JSONB_BUILD_OBJECT(),
    "created_at" timestamptz(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz(0) NULL,
    UNIQUE ("token")
)
;

CREATE TABLE public."clients" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR NOT NULL,
    "business_name" VARCHAR NULL, -- Nombre comercial si aplica
    "ruc" VARCHAR NULL, -- RUC si aplica
    "email" VARCHAR NOT NULL,
    "phone" VARCHAR NULL,
    "address" VARCHAR NULL,
    "created_at" TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(0) NULL,
    UNIQUE ("email")
)
;
